export const eventMetrics = [
    "# of Sales",
    "Rev",
    "Cash",
    "ROAS Rev",
    "ROAS Cash",
    "newLeads",
    "totalLeads",
    "Total Applications",
    "Q Apps",
    "unqualifiedApplications",
    "totalCalls",
    "qualifiedCalls",
    "unqualifiedCalls",
    "confirmedCalls",
    "callsShowed",
    "liveCalls",
    "totalCallsWithSalesRep",
    "qualifiedCallsWithSalesRep",
    "unqualifiedCallsWithSalesRep",
    "confirmedCallsWithSalesRep",
    "callsShowedWithSalesRep",
    "liveCallsWithSalesRep",
    "totalCallsWithSetter",
    "qualifiedCallsWithSetter",
    "unqualifiedCallsWithSetter",
    "confirmedCallsWithSetter",
    "callsShowedWithSetter",
    "liveCallsWithSetter",
    "totalSets",
    "outboundSets",
    "inboundSets",
    "setsNewOpportunity",
    "qualifiedSalesRepOpportunity",
    "totalQualifiedOpportunity",
    "newQualifiedOpportunity",
    "totalOffersMade",
    "totalAddToCart",
    "totalCustomEvents",
    "clicks",
    "ctr",
    "costPerClick",
    "linkClicks",
    "linkCtr",
    "costPerLinkClick",
    "impressions",
    "cpm",
    "reach",
    "videoWatchPercent",
    "thumbScrollStopRate",
    "clickQuality",
    "googleClicks",
    "googleCtr",
    "googleCostPerClick",
    "googleImpressions",
    "googleReach",
    "googleVideoWatchPercent",
];

export const metricDescriptions = {
    CPS: "Cost Per Sale",
    Rev: "Revenue: The total amound billed for the sales",
    Cash: "Cahs Collected: The amount of money that has been collected from orders",
    "ROAS Rev": "The return on ad spend based on revenue (revenue/ ad spend)",
    "ROAS Cash":
        "The return on ad spend based on the amount of money collected (Cash)",
    "N Leads": "# of new lead form submissions",
    Leads: "# of total lead form submissions",
    Apps: "# of applications",
    "Q Apps": "# of qualified applications",
    "UQ Apps": "# of unqualified applications",
    BC: "# of booked calls",
    "Q BC": "# of qualified booked calls",
    "UQ BC": "# of unqualified booked calls",
    "CFM BC": "# of confirmed booked calls",
    "BC Sh": "# of booked calls showed",
    "BC SR": "# of booked calls with sales reps",
    "Q BC R": "# of qualified booked calls sales reps",
    "UQ BC SR": "# of unqualified booked calls with sales reps",
    "CFM BC SR": "# of confirmed booked calls with sales rep",
    "BC Sh SR": "# of booked calls showed with sales rep",
    "BC AS": "# of booked cals with appointment setter",
    "Q BC AS": "# of qualified booked calls with appointment setter",
    "UQ BC AS": "# of unqualified booked calls with appointment setter",
    "CFM BC AS": "# of confirmed booked calls with appointment setter",
    "BC Sh AS": "# of booked calls showed with appointment setter",
    Sets: "# of sets",
    "OB Sets":
        "# of outbound sets (The number of sets made that have not booked a call in the last 30 days)",
    "IB Sets":
        "# of inbound sets (# of sets from prospects that have booked a call in the last 30 days)",
    "NO Sets":
        "# of new opportuntiy sets (Number of sets that have not been a qualified booked call in the last 30 days)",
    "Sets Sh": "# of shows to a sales call from sets",
    "Sets Sh Perc": "Show % from sets",
    QO: "# of qualified opportunity (Qualified booked calls plus sets)",
    "QO Sh": "# of qualified opportunity showed to a sales call",
    "QO Sh Perc": "Show % of qualified opportunity",
    NQO: "# of new qualified opportunity (Number of unique qualified calls and sets in the last 30 days)",
    "NQO Sh": "# of new qualified oppotunity calls showed with sales rep",
    "NQO Sh Perc": "Show % of new qualified opportunity calls",
    OM: "# of offers made to prospects",
    ATC: "# of add to carts",
    CTR: "Click Through Rate on meta ads",
    CPC: "Cost per click on meta",
    "Link Clicks": "Link clicks from meta",
    "Link CTR": "Link CTR (Click Through Rate) from meta",
    "CP Link Click": "Cost per link click from meta",
    Imp: "Impressions on meta",
    CPM: "Cost per thousand impressions on meta",
    Reach: "Reach on meta",
    "Vid Watch Perc": "Video watch % from ads on meta",
    TSSR: "Thumscroll Stop Rate from video ads on meta (This is 3 second video views/ impressions) to see the hook effectiveness of ads",
    "Click Q":
        "Click quality (this is link clicks from meta compared to the amount of non bot landing page views we detected)",
    Clicks: "Clicks on ads on google",
    "CTR Google": "Click Through Rate on ads on google",
    "CPC Google": "Cost per click on ads on google",
    "Imp Google": "Ad impressions on google",
    "CP N Lead": "Cost per new lead form submission",
    "CP Lead": "Cost per total lead form submissions",
    "CP App": "Cost per application",
    "CP Q App": "Cost per qualified application",
    "CP UQ App": "Cost per unqualifed application",
    "CP BC": "Cost per booekd call",
    "CP Q BC": "Cost per qualified booked call",
    "CP UQ BC": "Cost per unqualified booked calls",
    "CP CFM BC": "Cost per confirmed book call",
    "CP BC Sh": "Cost per booekd call that showed",
    "CP Set": "Cost per set",
    "CP OB Set": "Cost per outbound set",
    "CP IB Set": "Cost per inbound set",
    "CP NO Set": "Cost per new opportunity set",
    "CP Sets Sh": "Cost per set showed",
    "CP QO": "Cost per qualified opportunity",
    "CP QO Sh": "Cost per qualified opportunity that showed",
    "CP NQO": "Cost per new qualified opportunity",
    "CP NQO Sh": "Cost per new qualified opportunity that showed",
    "CP OM": "Cost per offer made",
};